### ISSUE TITLE
Support for making the source code of a UDF object available as a dataset attribute...

### ISSUE THREAD

**Issue by rhs3i** [lucasvr/hdf5-udf#15]
Would be great if the source of a UDF object could be included in the HDF5 file as a first class HDF5 object.  
* Would be useful in interesting ways to toolchains and UI built to take advantage of HDF5 with UDF, and
* Is consistent in a very appealing way with HDF5's property of a being "self-describing data".

**Comment by lucasvr** [comment]
Thanks for the suggestion! In fact, we have just checked-in a new feature to store the source code as a UDF metadata (see https://github.com/lucasvr/hdf5-udf/commit/0686419d7ae60f0fa4e2146645af583ffced059e for details).

A new tool should be made available soon to take benefit from that metadata (so that users can recompile the UDF making modifications as they see fit, for example). I'll keep this ticket open so I can refer to this issue number on future commits.
